(function (root) {
'use strict';
function parseCSV(text) {
  text=String(text||'').replace(/^\uFEFF/,'');
  var first=text.split(/\r?\n/,1)[0]||'', counts={',':0,';':0,'\t':0}, q=false;
  for(var i=0;i<first.length;i++){var c=first[i];if(c==='"')q=!q;else if(!q&&counts.hasOwnProperty(c))counts[c]++;}
  var delim=counts[';']>counts[',']?';':','; if(counts['\t']>counts[delim])delim='\t';
  var rows=[],row=[],field='',inQ=false,i=0;
  while(i<text.length){var ch=text[i];
    if(inQ){if(ch==='"'&&text[i+1]==='"'){field+='"';i+=2;continue;}if(ch==='"'){inQ=false;i++;continue;}field+=ch;i++;continue;}
    if(ch==='"'){inQ=true;i++;continue;} if(ch===delim){row.push(field);field='';i++;continue;} if(ch==='\r'){i++;continue;} if(ch==='\n'){row.push(field);rows.push(row);row=[];field='';i++;continue;} field+=ch;i++;
  }
  if(field!==''||row.length){row.push(field);rows.push(row);} return rows.filter(function(r){return r.some(function(f){return f.trim()!=='';});});
}
var ALIASES={name:['name','title','restaurant','place','restaurant name'],info:['info','description','about','summary'],note:['note','notes'],comment:['comment','comments'],url:['url','link','maps','map','google maps','maps url','map url','google maps url'],cuisine:['cuisine','cuisines','type','types','category'],food:['food','foods','dish','dishes','specialty','specialties'],area:['area','location','district','neighbourhood','neighborhood','region'],meal:['meal','meals'],occasion:['occasion','occasions','vibe','mood'],price:['price','price range','budget','cost'],photo:['photo','image','picture','img','photo url','image url','pic'],been:['been','visited','have been','tried'],mon:['mon','monday'],tue:['tue','tues','tuesday'],wed:['wed','wednesday'],thu:['thu','thur','thurs','thursday'],fri:['fri','friday'],sat:['sat','saturday'],sun:['sun','sunday']};
function headerKey(h){var s=String(h||'').trim().toLowerCase();for(var k in ALIASES)if(ALIASES[k].indexOf(s)!==-1)return k;return null;}
function splitList(s){return String(s||'').split(/[;|,\u3001\uFF0C\n]/).map(function(x){return x.trim();}).filter(Boolean);}
function isHttp(u){return /^https?:\/\//i.test(u||'');}
function cleanPhoto(p){p=String(p||'').trim();if(!p)return '';if(isHttp(p))return p;if(/^[a-z][a-z0-9+.\-]*:/i.test(p)||p.indexOf('//')===0)return '';p=p.replace(/^\.?\//,'');if(!p||p.split('/').indexOf('..')!==-1)return '';return p.indexOf('%')===-1?encodeURI(p):p;}
function toRestaurants(rows){if(!rows||rows.length<2)return [];var keys=rows[0].map(headerKey),out=[],seen={};for(var r=1;r<rows.length;r++){var o={};for(var c=0;c<keys.length;c++){var k=keys[c];if(k&&o[k]===undefined&&rows[r][c]!==undefined)o[k]=String(rows[r][c]).trim();}if(!o.name)continue;var cuisine=splitList(o.cuisine);if(!cuisine.length)cuisine=splitList(o.tags);var rest={name:o.name,info:[o.note,o.info,o.comment].filter(Boolean).join(' · '),url:isHttp(o.url)?o.url:'',photo:cleanPhoto(o.photo),been:(o.been||'').trim(),cuisines:cuisine,foods:splitList(o.food),meals:splitList(o.meal),areas:splitList(o.area),occasions:splitList(o.occasion),price:(o.price||'').trim(),hours:{mon:o.mon||'',tue:o.tue||'',wed:o.wed||'',thu:o.thu||'',fri:o.fri||'',sat:o.sat||'',sun:o.sun||''}};rest.id=(rest.name+'|'+(rest.url||rest.areas.join(','))).toLowerCase();if(!seen[rest.id]){seen[rest.id]=1;out.push(rest);}}return out;}
function parseRestaurants(t){return toRestaurants(parseCSV(t));}
function facetsOf(list){var f={meals:{},cuisines:{},foods:{},areas:{},occasions:{},prices:{},been:{}};function add(b,v){var k=v.toLowerCase();if(!b[k])b[k]=v;}list.forEach(function(r){r.meals.forEach(function(v){add(f.meals,v);});r.cuisines.forEach(function(v){add(f.cuisines,v);});r.foods.forEach(function(v){add(f.foods,v);});r.areas.forEach(function(v){add(f.areas,v);});r.occasions.forEach(function(v){add(f.occasions,v);});if(r.price)add(f.prices,r.price);if(r.been)add(f.been,r.been);});function arr(b){return Object.keys(b).sort().map(function(k){return b[k];});}return{meals:arr(f.meals),cuisines:arr(f.cuisines),foods:arr(f.foods),areas:arr(f.areas),occasions:arr(f.occasions),prices:arr(f.prices),been:arr(f.been)};}
function lowerSet(a){var s={};(a||[]).forEach(function(v){s[String(v).toLowerCase()]=1;});return s;}function anyIn(v,s){return v.some(function(x){return s[x.toLowerCase()];});}
function filterRestaurants(list,sel,hidden){sel=sel||{};var m=lowerSet(sel.meals),c=lowerSet(sel.cuisines),f=lowerSet(sel.foods),a=lowerSet(sel.areas),o=lowerSet(sel.occasions),p=lowerSet(sel.prices),b=lowerSet(sel.been),hs={};(hidden||[]).forEach(function(id){hs[id]=1;});var has=function(s){return Object.keys(s).length>0;};return list.filter(function(r){if(hs[r.id])return false;if(has(m)&&!anyIn(r.meals,m))return false;if(has(c)&&!anyIn(r.cuisines,c))return false;if(has(f)&&!anyIn(r.foods,f))return false;if(has(a)&&!anyIn(r.areas,a))return false;if(has(o)&&!anyIn(r.occasions,o))return false;if(has(p)&&!(r.price&&p[r.price.toLowerCase()]))return false;if(has(b)&&!b[String(r.been||'').toLowerCase()])return false;return true;});}
function shuffle(a,rand){rand=rand||Math.random;a=a.slice();for(var i=a.length-1;i>0;i--){var j=Math.floor(rand()*(i+1)),t=a[i];a[i]=a[j];a[j]=t;}return a;}
function mapsLink(r){if(r.url)return r.url;return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent([r.name].concat(r.areas.slice(0,1)).join(' '));}
var EMOJI=[[/dim sum|cantonese|chinese|roast|congee|noodle|wonton/i,'🥟'],[/hot ?pot|shabu|bbq|barbecue|grill|yakiniku|korean/i,'🍲'],[/sushi|japan|ramen|izakaya|udon/i,'🍣'],[/pizza|ital|pasta/i,'🍕'],[/burger|american|fast|diner/i,'🍔'],[/cafe|coffee|brunch|bakery|dessert|sweet|tea/i,'☕'],[/thai|viet|indian|curry|spicy|sichuan/i,'🍛'],[/seafood|crab|fish/i,'🦀'],[/bar|pub|cocktail|beer/i,'🍻'],[/vegan|vegetarian|salad|health/i,'🥗'],[/western|steak|french/i,'🥩']];
function emojiFor(r){var s=r.cuisines.concat(r.foods).join(' ')+' '+r.name;for(var i=0;i<EMOJI.length;i++)if(EMOJI[i][0].test(s))return EMOJI[i][1];return '🍽️';}
var api={parseCSV:parseCSV,parseRestaurants:parseRestaurants,toRestaurants:toRestaurants,facetsOf:facetsOf,filterRestaurants:filterRestaurants,shuffle:shuffle,mapsLink:mapsLink,emojiFor:emojiFor,splitList:splitList,cleanPhoto:cleanPhoto};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.FF=api;
})(typeof self!=='undefined'?self:this);
